import { db } from "./index";
import { scenarios, committeeNotes, rebalanceEvents } from "./schema";

export async function seedDatabase() {
  // Check if already seeded
  const existingScenarios = await db.select().from(scenarios);
  if (existingScenarios.length > 0) {
    return;
  }

  // 1. Initial Committee Scenarios
  await db.insert(scenarios).values([
    {
      name: "Base Case — Steady Balance Sheet Integration",
      scenarioType: "base",
      loanGrowth: 14.5,
      nim: 3.55,
      creditCostBps: 45,
      costToIncome: 39.2,
      exitPbMultiple: 2.45,
      horizonYears: 3,
      transactionCostBps: 25,
      projectedPat: 74850,
      projectedBvps: 372.4,
      targetPrice: 912.38,
      upsidePercent: 24.8,
      notes: "Assumes gradual replacement of high-cost wholesale borrowing inherited from HDFC Ltd with retail CASA deposits over 36 months. NIM stabilizes around 3.55%. Credit costs remain benign at 45 bps.",
      createdBy: "Lead BFSI Analyst",
    },
    {
      name: "Bull Case — Accelerated CASA Accretion & Multiple Expansion",
      scenarioType: "bull",
      loanGrowth: 17.5,
      nim: 3.75,
      creditCostBps: 35,
      costToIncome: 37.8,
      exitPbMultiple: 2.85,
      horizonYears: 3,
      transactionCostBps: 25,
      projectedPat: 84600,
      projectedBvps: 391.8,
      targetPrice: 1116.63,
      upsidePercent: 52.7,
      notes: "Branch expansion (1,500+ new branches) yields rapid CASA market share capture. Mortgage cross-selling accelerates to 40%+. NIM expands to 3.75%. ROE returns to pre-merger 17.2%. P/B expands to 2.85x.",
      createdBy: "Chief Investment Officer",
    },
    {
      name: "Bear Case — NIM Compression & Prolonged Liability Pressure",
      scenarioType: "bear",
      loanGrowth: 10.5,
      nim: 3.25,
      creditCostBps: 75,
      costToIncome: 42.0,
      exitPbMultiple: 1.85,
      horizonYears: 3,
      transactionCostBps: 30,
      projectedPat: 59200,
      projectedBvps: 348.6,
      targetPrice: 644.91,
      upsidePercent: -11.8,
      notes: "Severe competition for retail deposits keeps cost of funds elevated. NIM contracts to 3.25%. Unsecured retail delinquencies increase credit costs to 75 bps. P/B de-rates to 1.85x.",
      createdBy: "Risk Management Committee",
    },
    {
      name: "Stress Test — RBI Repo Hike +100bps & Liquidity Tightening",
      scenarioType: "stress",
      loanGrowth: 9.0,
      nim: 3.15,
      creditCostBps: 90,
      costToIncome: 43.5,
      exitPbMultiple: 1.70,
      horizonYears: 2,
      transactionCostBps: 35,
      projectedPat: 51800,
      projectedBvps: 334.2,
      targetPrice: 568.14,
      upsidePercent: -22.3,
      notes: "Simulates severe liquidity squeeze, deposit re-pricing lag, and treasury mark-to-market bond portfolio impairment. Capital adequacy remains solid at 17.8% CET-1, well above regulatory buffer.",
      createdBy: "Stress Testing Unit",
    },
  ]);

  // 2. Investment Committee Audit Notes
  await db.insert(committeeNotes).values([
    {
      author: "Vikramaditya Sharma, CFA",
      role: "Head of BFSI Research",
      category: "fundamental",
      title: "HDFC Ltd Post-Merger Balance Sheet Amalgamation & NIM Transition Audit",
      content: "Following the July 1, 2023 merger of Housing Development Finance Corporation (HDFC Ltd) into HDFC Bank, the loan book expanded by ~55% with ₹6.2 Lakh Cr mortgage advances. While this compressed reported NIM from 4.1% to 3.44%-3.50% due to regulatory SLR/CRR drag on wholesale borrowings, core asset quality remains pristine with GNPA at 1.24% and NNPA at 0.33%. CET-1 of 17.5% provides a 950 bps buffer above RBI Basel III requirements.",
      recommendation: "OVERWEIGHT",
      targetAllocationPct: 34.0,
      status: "approved",
      classification: "HISTORICAL_OBSERVATION",
    },
    {
      author: "Ananya Deshmukh",
      role: "Senior Quantitative Portfolio Manager",
      category: "active_allocation",
      title: "Active Strategy Alpha Generation & Turnover Friction Review",
      content: "Active mandate maintains a +450 bps tactical tilt in HDFC Bank (34.0% vs benchmark weight of 29.5% in Nifty Bank). Annualized 3-Year Active Alpha stands at +2.84% gross and +2.18% net of transaction costs (25 bps round-trip friction, 14.2% portfolio turnover). Information Ratio is 0.72 with tracking error capped at 3.94%. Rebalancing rule enforced at 2.5% absolute drift.",
      recommendation: "OVERWEIGHT",
      targetAllocationPct: 34.0,
      status: "approved",
      classification: "CALCULATED_METRIC",
    },
    {
      author: "Siddharth Sen, FRM",
      role: "Chief Risk Officer",
      category: "macro_risk",
      title: "Macro Stress Scenarios & LDR (Loan-to-Deposit Ratio) Normalization",
      content: "HDFC Bank's incremental credit-to-deposit ratio has moderated from 110% post-merger towards 98%. Management target of 85-90% requires pacing loan growth below deposit growth for the next 18-24 months. Sensitivity models indicate that each 10 bps expansion in NIM delivers ~₹3,200 Cr incremental PAT.",
      recommendation: "MONITOR",
      targetAllocationPct: 31.0,
      status: "approved",
      classification: "SCENARIO_ASSUMPTION",
    },
    {
      author: "Pooja Singhania, CMT",
      role: "Technical Strategist",
      category: "technical",
      title: "Multi-Timeframe Technical Setup: 200 DMA Confluence & RSI Divergence",
      content: "Price is consolidating in the ₹710-₹745 range (bonus-adjusted). 200 DMA stands at ₹708.20 providing strong institutional floor. RSI(14) has reset to 54.2 (neutral-bullish), resolving previous overbought conditions. 50 DMA is curling above 200 DMA indicating emerging structural base. Immediate resistance at ₹765 (pivot R1).",
      recommendation: "EQUAL_WEIGHT",
      targetAllocationPct: 32.5,
      status: "approved",
      classification: "INTERPRETATION",
    },
  ]);

  // 3. Rebalance Events Log
  await db.insert(rebalanceEvents).values([
    {
      eventDate: "2025-08-27",
      strategy: "Active Bank Alpha",
      triggerType: "Corporate Action",
      assetTraded: "HDFCBANK.NS",
      action: "REBALANCE",
      weightBefore: 33.8,
      weightAfter: 34.0,
      turnoverPct: 0.4,
      costBps: 15.0,
      realizedFrictionInr: 15000,
      status: "Executed",
    },
    {
      eventDate: "2025-06-30",
      strategy: "Active Bank Alpha",
      triggerType: "Quarterly Scheduled",
      assetTraded: "ICICIBANK.NS / HDFCBANK.NS",
      action: "BUY",
      weightBefore: 31.5,
      weightAfter: 33.8,
      turnoverPct: 2.3,
      costBps: 25.0,
      realizedFrictionInr: 57500,
      status: "Executed",
    },
    {
      eventDate: "2025-03-31",
      strategy: "Passive Nifty Bank Replication",
      triggerType: "Quarterly Scheduled",
      assetTraded: "Nifty Bank Basket",
      action: "REBALANCE",
      weightBefore: 29.8,
      weightAfter: 29.5,
      turnoverPct: 0.8,
      costBps: 10.0,
      realizedFrictionInr: 10000,
      status: "Executed",
    },
    {
      eventDate: "2024-12-31",
      strategy: "Active Bank Alpha",
      triggerType: "Drift Threshold >2.5%",
      assetTraded: "KOTAKBANK.NS / HDFCBANK.NS",
      action: "BUY",
      weightBefore: 29.0,
      weightAfter: 32.0,
      turnoverPct: 3.0,
      costBps: 25.0,
      realizedFrictionInr: 75000,
      status: "Executed",
    },
    {
      eventDate: "2024-09-30",
      strategy: "Active Bank Alpha",
      triggerType: "Quarterly Scheduled",
      assetTraded: "HDFCBANK.NS",
      action: "BUY",
      weightBefore: 27.2,
      weightAfter: 29.5,
      turnoverPct: 2.3,
      costBps: 25.0,
      realizedFrictionInr: 57500,
      status: "Executed",
    },
  ]);
}
